name: Build Site

on:
  push:
    branches: [master, main]
    paths:
      - '**.md'
      - 'build.js'
      - 'builder/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: node build.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[CI] Auto-generate HTML from markdown"
          file_pattern: "**.html"
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
